### PR TITLE
feat: add sass gem install command

### PR DESCRIPTION
**Pull request by dipscom**

### CODE REVIEW

**Comment by joemidi** [comment]
We could actually change it to use [node-sass](https://www.npmjs.com/package/node-sass) instead, which is a C version of SASS, that way we don't need the ruby gem dependency.

**Comment by dipscom** [comment]
The less things to install, the better. That sounds like a good idea.

**Comment by pyramidium** [comment]
pyramidium/generator-bannertime#33

**Comment by joemidi** [comment]
Cool, we're going to close this then, and change it to use node-sass.

**Pull request closed without merging**
